# Site settings
# in the templates available like {{ site.myvariable }}.
title: New start of XJC
email: 3103887573@qq.com
brand: XJC
headline: student in XJU
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.xujuncheng.cn" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 3103887573@qq.com
phone: 12315

# Tracking
googleAnalitycsID: 000

